### ISSUE TITLE
Error in stock scrapper: Enterprise value is "N/A"

### ISSUE THREAD

**Issue by Gunnharm** [damdalf/Personal-Projects#14]
I launched stock_test.py and got this error (stdout and stderr in out.txt file)
Probably its bug on the Yahoo side but I think it is better to check for that in your program
[out.txt](https://github.com/damdalf/Personal-Projects/files/9222797/out.txt)
![issue](https://user-images.githubusercontent.com/87275683/181831936-3de7cf53-03ae-41ac-ae70-511e874a478c.png)

**Comment by Gunnharm** [comment]
After a while that page became this
![image](https://user-images.githubusercontent.com/87275683/181832765-b682a09c-30c2-42a2-96ac-cabab67e2d12.png)

**Comment by Damdahlf** [comment]
Thank you! I do think it was an error on Yahoo's side, but it's definitely a good idea for the program to check for this and handle the error accordingly. I look forward to resolving this!

Best,

Devin

**Comment by Damdahlf** [comment]
I added a few bare-minimum checks that should prevent this from happening, or at least attempting to wait and retrieve the information a second (and third) time. Please let me know if you encounter this error again. It was definitely on Yahoo's side of things, but more improved methods of handling these kinds of situations will be added eventually!
